project:
  title: "Primordial Machine"
  type: website
  output-dir: ./../.upload/index

format:
  html:
    theme: cosmo
    css: custom-css/style.css

website:
  site-url: 'https://develop.primordialmachine.com/'
  title: "Primordial Machine"
  favicon: ./favicon.ico
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Forum"
        href: "https://develop.primordialmachine.com/forums/"
        target: "_blank"
      - href: "https://github.com/primordialmachine/primordialmachine"
        target: "_blank"
        text: GitHub
      - sidebar:publications
      - about.qmd

  sidebar:
    - id: "publications"
      title: "Publications"
      style: "docked"
      contents:
      - href: https://develop.primordialmachine.com/ddl-specification
        text: "DDL Specification"
      - href: https://develop.primordialmachine.com/adl-specification
        text: "ADL Specification"
      - href: https://develop.primordialmachine.com/mathematical-foundations
        text: "Mathematical Foundations"