#if !defined(CORE_TESTS_UTF8_INLINEUTF8ITERATORTESTS_H_INCLUDED)
#define CORE_TESTS_UTF8_INLINEUTF8ITERATORTESTS_H_INCLUDED

#include "dx/core.h"

Core_Result Core_Tests_Utf8_inlineUtf8IteratorTests();

#endif // CORE_TESTS_UTF8_INLINEUTF8ITERATORTESTS_H_INCLUDED
