#if !defined(CORE_TESTS_UTF8_INLINEBYTEITERATORTESTS_H_INCLUDED)
#define CORE_TESTS_UTF8_INLINEBYTEITERATORTESTS_H_INCLUDED

#include "dx/core.h"

Core_Result Core_Tests_Utf8_inlineByteIteratorTests();

#endif // CORE_TESTS_UTF8_INLINEBYTEITERATORTESTS_H_INCLUDED
