#if !defined(CORE_TESTS_FILESYSTEM_GETFILECONTENTSTESTS_H_INCLUDED)
#define CORE_TESTS_FILESYSTEM_GETFILECONTENTSTESTS_H_INCLUDED

#include "dx/core.h"

Core_Result Core_Tests_FileSystem_getFileContentsTests();

#endif // CORE_TESTS_FILESYSTEM_GETFILECONTENTSTESTS_H_INCLUDED
