#if !defined(CORE_TESTS_FILESYSTEM_GETFILECONTENTSCALLBACKTESTS_H_INCLUDED)
#define CORE_TESTS_FILESYSTEM_GETFILECONTENTSCALLBACKTESTS_H_INCLUDED

#include "dx/core.h"

Core_Result Core_Tests_FileSystem_getFileContentsCallbackTests();

#endif // CORE_TESTS_FILESYSTEM_GETFILECONTENTSCALLBACKTESTS_H_INCLUDED
