#if !defined(CORE_TESTS_FILESYSTEM_GETFILECONTENTSMEMORYMAPPEDCALLBACKTESTS_H_INCLUDED)
#define CORE_TESTS_FILESYSTEM_GETFILECONTENTSMEMORYMAPPEDCALLBACKTESTS_H_INCLUDED

#include "dx/core.h"

Core_Result Core_Tests_FileSystem_getFileContentsMemoryMappedCallbackTests();

#endif // CORE_TESTS_FILESYSTEM_GETFILECONTENTSMEMORYMAPPEDCALLBACKTESTS_H_INCLUDED
