DEFINE(PFNGLGETINTEGERVPROC, glGetIntegerv, NULL)
DEFINE(PFNGLGETSTRINGPROC, glGetString, NULL)
DEFINE(PFNGLGETSTRINGIPROC, glGetStringi, NULL)

DEFINE(PFNGLFLUSHPROC, glFlush, NULL)

DEFINE(PFNGLVIEWPORTPROC, glViewport, NULL)
DEFINE(PFNGLSCISSORPROC, glScissor, NULL)
DEFINE(PFNGLCLEARCOLORPROC, glClearColor, NULL)
DEFINE(PFNGLCLEARDEPTHPROC, glClearDepth, NULL)
DEFINE(PFNGLCLEARDEPTHFPROC, glClearDepthf, NULL)
DEFINE(PFNGLCLEARPROC, glClear, NULL)
DEFINE(PFNGLDEPTHMASKPROC, glDepthMask, NULL)
DEFINE(PFNGLDEPTHFUNCPROC, glDepthFunc, NULL)

DEFINE(PFNGLBLENDFUNCPROC, glBlendFunc, NULL)

DEFINE(PFNGLCULLFACEPROC, glCullFace, NULL)

DEFINE(PFNGLENABLEPROC, glEnable, NULL)
DEFINE(PFNGLDISABLEPROC, glDisable, NULL)
DEFINE(PFNGLGETERRORPROC, glGetError, NULL)

DEFINE(PFNGLGENBUFFERSPROC, glGenBuffers, NULL)
DEFINE(PFNGLDELETEBUFFERSPROC, glDeleteBuffers, NULL)
DEFINE(PFNGLBINDBUFFERPROC, glBindBuffer, NULL)
DEFINE(PFNGLBUFFERDATAPROC, glBufferData, NULL)

DEFINE(PFNGLCREATESHADERPROC, glCreateShader, NULL)
DEFINE(PFNGLSHADERSOURCEPROC, glShaderSource, NULL)
DEFINE(PFNGLCOMPILESHADERPROC, glCompileShader, NULL)
DEFINE(PFNGLDELETESHADERPROC, glDeleteShader, NULL)
DEFINE(PFNGLGETSHADERIVPROC, glGetShaderiv, NULL)
DEFINE(PFNGLCREATEPROGRAMPROC, glCreateProgram, NULL)
DEFINE(PFNGLDELETEPROGRAMPROC, glDeleteProgram, NULL)
DEFINE(PFNGLATTACHSHADERPROC, glAttachShader, NULL)
DEFINE(PFNGLLINKPROGRAMPROC, glLinkProgram, NULL)
DEFINE(PFNGLGETPROGRAMIVPROC, glGetProgramiv, NULL)
DEFINE(PFNGLUSEPROGRAMPROC, glUseProgram, NULL)
DEFINE(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog, NULL)

DEFINE(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer, NULL)
DEFINE(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray, NULL)
DEFINE(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays, NULL)
DEFINE(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays, NULL)
DEFINE(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray, NULL)

DEFINE(PFNGLDRAWARRAYSPROC, glDrawArrays, NULL)

DEFINE(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv, NULL)
DEFINE(PFNGLUNIFORM4FVPROC, glUniform3fv, NULL)
DEFINE(PFNGLUNIFORM4FVPROC, glUniform4fv, NULL)
DEFINE(PFNGLUNIFORM1IPROC, glUniform1i, NULL)
DEFINE(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation, NULL)

DEFINE(PFNGLGENTEXTURESPROC, glGenTextures, NULL)
DEFINE(PFNGLDELETETEXTURESPROC, glDeleteTextures, NULL)
DEFINE(PFNGLTEXPARAMETERIPROC, glTexParameteri, NULL)
DEFINE(PFNGLTEXPARAMETERFVPROC, glTexParameterfv, NULL)
DEFINE(PFNGLBINDTEXTUREPROC, glBindTexture, NULL)
DEFINE(PFNGLTEXIMAGE2DPROC, glTexImage2D, NULL)
DEFINE(PFNGLACTIVETEXTUREPROC, glActiveTexture, NULL)

DEFINE(PFNGLPIXELSTOREIPROC, glPixelStorei, NULL)
